---
- name: copy a config of iptables
  copy:
    src: ../files/ntp.conf
    dest: /etc/ntp.conf
  become: yes
- name: enable and restart iptables
  systemd:
    name: ntp.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
