---
- name: disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    insertafter: "^#PermitRootLogin"
    line: "PermitRootLogin no"
- name: disable ipv6
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "AddressFamily inet"
- name: restart sshd
  systemd:
    name: ssh.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
